version: '3.5'

services:
  mariadb:
    image: mariadb:10.11
    container_name: zabbix-mariadb
    restart: always
    environment:
      MARIADB_DATABASE: zabbix
      MARIADB_USER: zabbix
      MARIADB_PASSWORD: zabbix
      MARIADB_ROOT_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    volumes:
      - mariadb-data:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:6.4.0-ubuntu
    container_name: zabbix-server
    restart: always
    depends_on:
      - mariadb
    environment:
      DB_SERVER_HOST: mariadb
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_ALLOWUNSUPPORTEDDBVERSIONS: "1"
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:6.4.0-ubuntu
    container_name: zabbix-web
    restart: always
    depends_on:
      - mariadb
      - zabbix-server
 environment:
      DB_SERVER_HOST: mariadb
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Africa/Casablanca
    ports:
      - "80:8080"

volumes:
  mariadb-data: